### PR TITLE
Fixed scraping for Bengaluru Hospitalization Data

### PR DESCRIPTION
**Pull request by s-mandeep**
~~Fixed the issue described for Bengaluru Hospitalization Data described at [https://github.com/DataKind-BLR/covid19bharat_scrapers/issues/75](https://github.com/DataKind-BLR/covid19bharat_scrapers/issues/75).~~

> If a screenshot could be captured automatically daily, it should be possible to get O2/ICU/HDU occupancy using OCR

This fix doesn't use a screenshot to capture the data, instead uses raw HTML elements from selenium.

**It works for my local repo, but it should work for Github Actions as well** since it is fetching from this link [ https://apps.bbmpgov.in/Covid19/en/bedstatus.php](https://apps.bbmpgov.in/Covid19/en/bedstatus.php)

**So, after testing this fix using Github actions, I found out that doesn't work.**

### CODE REVIEW

**Comment by grill05** [comment]
Hi, thanks for working on this

Yes, I get the same error Error: net::ERR_NAME_NOT_RESOLVED. Basically the github actions host is unable to reach the IP address of the PowerBI datasheet

One possible way of fixing this is to use a reliable Indian proxy server. But I couldn't get than to work (request timed out) when I tried that

You can uncomment L39-40 in the workflow file (test.yml)
 - name: Setup upterm session
    uses: lhotari/action-upterm@v1

This will give you direct ssh access to the running github actions host, which is useful for debugging

**Comment by grill05** [comment]
If you know some other alternative way to automate this (so that scraper.py runs daily at the predetermined time), then that could also work

I used github actions because it comes free with github, and is relatively easy to use/learn..

**Comment by s-mandeep** [comment]
Hi! Right, the issue is essentially what you described. One possible solution I thought of was to host this script as an Azure function. This can be done for free if you have a student account. I will try doing this in my free time but I don't know if I will be free now for some time.

**Comment by s-mandeep** [comment]
Hey! I have finally implemented the auto-scraping for BLR (works with Actions too). I have merged the conflicts, so you that you can accept the pull request.

**Comment by grill05** [comment]
thanks. Your solution (using tabula-py on the bengaluru bulletin pdfs) is quite elegant

Nice work!

**Comment by grill05** [comment]
I've copy-pasted your code into scraper.py, and its working well. Unfortunately, I'm not really sure how to resolve conficts in a PR. If something breaks, the hospital dashboard/tracker that uses these auto-generated csv will also crash 😌

So closing the PR. Thanks a lot for fixing this. 🙏

**Comment by s-mandeep** [comment]
No issues, happy I could help before running a fever myself 😂. Hopefully, it's nothing major

**Pull request closed without merging**
